"""fix updated_at

Revision ID: c90e7fee53b1
Revises: c74379425856
Create Date: 2025-01-23 06:57:15.623697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c90e7fee53b1"
down_revision: Union[str, None] = "c74379425856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_column("users", "updtaed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updtaed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
